// HelpContent.h - curated, offline troubleshooting reference text baked
// directly into the executable. This is the point of the whole project:
// when Microsoft's online troubleshooters and support docs aren't reachable
// (because the internet is exactly what's broken), this text is still here.
// Original content, written for this project - not copied from any vendor
// documentation.
#pragma once
#include <string>

inline std::wstring GetOfflineHelpText() {
    return
L"WinDiagPro Offline Troubleshooting Reference\r\n"
L"=============================================\r\n"
L"This text is built into the program - it works with no internet connection\r\n"
L"and no access to Microsoft's (or anyone else's) support servers. If you're\r\n"
L"reading this because the internet itself is down, you're in the right place.\r\n"
L"\r\n"
L"--------------------------------------------------------------------\r\n"
L"1. \"The internet doesn't work\" - where to actually look first\r\n"
L"--------------------------------------------------------------------\r\n"
L"Work through these in order - each one rules out a whole category before\r\n"
L"you touch anything more invasive:\r\n"
L"\r\n"
L"  a) Network tab: is the adapter you actually use even connected? A\r\n"
L"     disconnected or disabled adapter looks nothing like a DNS or gateway\r\n"
L"     problem, but produces the same symptom (\"nothing loads\").\r\n"
L"  b) Topology tab: does that adapter show green (Routed) or something else?\r\n"
L"     Red/orange/blue/gray all mean \"this adapter isn't actually providing\r\n"
L"     internet right now\", each for a different reason (see section 2).\r\n"
L"  c) Dashboard: what does the automatic diagnosis say the likely root\r\n"
L"     cause is? It's built to point at ONE thing rather than list every\r\n"
L"     symptom as equally important.\r\n"
L"  d) Only after (a)-(c): consider DNS, proxy, firewall, or a full reset.\r\n"
L"     Resetting things blindly before you know which layer is actually\r\n"
L"     broken just adds more moving parts to reason about.\r\n"
L"\r\n"
L"--------------------------------------------------------------------\r\n"
L"2. Reading the Topology tab colors\r\n"
L"--------------------------------------------------------------------\r\n"
L"  GREEN (Routed)     - Normal. Has an address and a working gateway.\r\n"
L"  RED (Gateway scope mismatch) - Has a 169.254.x.x (APIPA) address AND a\r\n"
L"     gateway is still attached to it. This combination is always wrong -\r\n"
L"     a 169.254.x.x address means DHCP has NOT succeeded, so nothing should\r\n"
L"     be trying to route through it. Fix: right-click the adapter in the\r\n"
L"     Network tab -> \"Release & renew DHCP on this adapter\". Don't reset\r\n"
L"     Winsock/TCP-IP for this - the problem is that one adapter's lease,\r\n"
L"     not the network stack.\r\n"
L"  BLUE (Direct link) - APIPA address, no gateway attached. This is CORRECT\r\n"
L"     behavior if this cable goes directly to another PC with no DHCP\r\n"
L"     server (no router in between). Nothing to fix.\r\n"
L"  ORANGE (Isolated)  - Has an address but no gateway at all. Expected on a\r\n"
L"     deliberately isolated/local-only network; otherwise check the\r\n"
L"     adapter's IP configuration.\r\n"
L"  GRAY (Disconnected) - Cable unplugged, Wi-Fi off, or adapter disabled.\r\n"
L"  PURPLE (Virtual)   - Hyper-V/WSL/VPN virtual switch. Not physical\r\n"
L"     hardware - if this is the only thing showing red/gray, that's not\r\n"
L"     your internet problem.\r\n"
L"\r\n"
L"--------------------------------------------------------------------\r\n"
L"3. \"Some websites load, others don't\" (partial/intermittent failures)\r\n"
L"--------------------------------------------------------------------\r\n"
L"This specific pattern almost never means \"the internet is down\" - full\r\n"
L"outages fail everything equally. Partial failure points at one of these:\r\n"
L"\r\n"
L"  - Hosts file has an entry redirecting a specific site (Security tab ->\r\n"
L"    \"Hosts file\" check). A hijacked hosts file is a classic cause and is\r\n"
L"    easy to miss because ping/gateway/DNS-server checks all look fine.\r\n"
L"  - A specific DNS server is down/slow but others work - try the DNS\r\n"
L"    server check results on the Network tab; consider changing the\r\n"
L"    adapter's DNS servers to a public resolver (1.1.1.1 / 8.8.8.8) as a\r\n"
L"    temporary test, via the adapter's properties in Network Connections.\r\n"
L"  - A proxy is configured and only some destinations are allowed through\r\n"
L"    it (Security tab -> proxy checks).\r\n"
L"  - A firewall or security product is blocking specific destinations\r\n"
L"    (check the Security tab's firewall profile status).\r\n"
L"  - The Gateway-scope-mismatch pattern in section 2 above, if you have\r\n"
L"    more than one adapter and traffic is bouncing between a working one\r\n"
L"    and a broken one depending on Windows' route selection.\r\n"
L"\r\n"
L"--------------------------------------------------------------------\r\n"
L"4. \"Websites give certificate/security errors\" but the network is fine\r\n"
L"--------------------------------------------------------------------\r\n"
L"Check the System tab's \"System clock / time sync\" result FIRST. HTTPS/TLS\r\n"
L"certificate validation depends on the system clock being roughly correct -\r\n"
L"a wrong date (common after a dead CMOS battery, or a fresh Windows install\r\n"
L"that hasn't synced yet) breaks secure sites while everything else on the\r\n"
L"network works completely normally. This is one of the most-overlooked\r\n"
L"causes because it doesn't look like a network problem at all.\r\n"
L"\r\n"
L"--------------------------------------------------------------------\r\n"
L"5. \"Windows Update is stuck / won't install anything\"\r\n"
L"--------------------------------------------------------------------\r\n"
L"  1. Check the System proxy (WinHTTP) result on the Security tab first -\r\n"
L"     Windows Update uses this proxy setting specifically, separately from\r\n"
L"     your browser's proxy. A leftover corporate/VPN proxy here is a very\r\n"
L"     common, easy-to-miss cause.\r\n"
L"  2. If that's clear, use the Repair tab's \"Full Windows Update Reset\".\r\n"
L"     It stops the relevant services, renames the update cache folders\r\n"
L"     out of the way (nothing is deleted - fully reversible), and restarts\r\n"
L"     the services. This fixes the common case of the service running but\r\n"
L"     never actually installing anything.\r\n"
L"  3. Still stuck? Run DISM CheckHealth/ScanHealth then SFC (System tab) -\r\n"
L"     a corrupt component store or system files can prevent updates from\r\n"
L"     installing even when the download itself works.\r\n"
L"\r\n"
L"--------------------------------------------------------------------\r\n"
L"6. Before you make any change: the reversible way to work\r\n"
L"--------------------------------------------------------------------\r\n"
L"  - Repair tab -> \"Backup Current Network Configuration\" takes a snapshot\r\n"
L"    of your current settings before you change anything, so you can\r\n"
L"    compare before/after.\r\n"
L"  - Repair tab -> \"Backup Network Drivers\" exports your adapters' driver\r\n"
L"    packages (already on this machine - nothing downloaded) so a driver\r\n"
L"    is available to reinstall offline if something ever goes wrong.\r\n"
L"  - Change ONE thing at a time and re-run the relevant scan before trying\r\n"
L"    the next thing. It's slower, but it's the only way to actually learn\r\n"
L"    which change fixed it (or made it worse).\r\n"
L"\r\n"
L"--------------------------------------------------------------------\r\n"
L"7. Low disk space symptoms (easy to misdiagnose as something else)\r\n"
L"--------------------------------------------------------------------\r\n"
L"Under roughly 5% free space, Windows can start behaving strangely in ways\r\n"
L"that look unrelated to disk space: Windows Update fails, background\r\n"
L"services silently stop working, and the System event log fills with\r\n"
L"unrelated-looking errors. If the System tab shows critically low free\r\n"
L"space alongside other odd symptoms, clear space FIRST and re-run\r\n"
L"diagnostics before chasing the other symptoms individually.\r\n"
L"\r\n"
L"--------------------------------------------------------------------\r\n"
L"About this list\r\n"
L"--------------------------------------------------------------------\r\n"
L"This is a fixed reference built into this version of the program. It "
L"won't cover every possible problem, but it's always available - "
L"copy/paste sections of it (or a saved Report) onto another device if you "
L"need to search for more detail once you do have a working connection "
L"somewhere.\r\n";
}
